server:
  port: 8500

cubic:
  employees:
    numbers: 200
  partners:
    numbers: 30
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news_portal
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL

    

   